export const {
  VITE_REACT_BACKEND_URL,
  VITE_REACT_FIREBASE_API_KEY,
  VITE_REACT_FIREBASE_AUTH_DOMAIN,
  VITE_REACT_FIREBASE_PROJECT_ID,
  VITE_REACT_FIREBASE_STORAGE_BUCKET,
  VITE_REACT_FIREBASE_MESSAGE_SENDER_ID,
  VITE_REACT_FIREBASE_APP_ID,
} = import.meta.env;
